#!/usr/bin/python2.6
import os
import sys
from subprocess import Popen, PIPE, STDOUT

command = '/usr/local/freeswitch/bin/fs_cli -x \"khomp summary\"'
critical = False;
num = []
disabled = ['00', '01', '02', '03', '04', '05']

p = Popen(command,shell=True, stdin=PIPE, stdout=PIPE, stderr=STDOUT)

for e in p.stdout:
      	if "serial" in e:
               	data = e.split(' ')
	if "DOWN" in e:
                if data[2] not in disabled:
       	                num.append(data[2])
               	        critical = True;

if critical:
       	print 'EBS '+ str(num) +' DOWN'
       	sys.exit(2) # CRITICAL

print 'all EBS are OK'
sys.exit(0) #OK
