#!/bin/sh

set -e

PKG=wirephone-monit-config

if [ "$1" = configure ] ; then
	dpkg-divert --add --package ${PKG} --rename \
		--divert /etc/monit/monitrc.distrib /etc/monit/monitrc
	[ \! -e /etc/monit/monitrc -o -L /etc/monit/monitrc ] && ln -sf /etc/site/monit/monitrc /etc/monit/monitrc
	invoke-rc.d monit restart
fi
#DEBHELPER#
exit 0
