#!/usr/bin/python2.7
# encoding: utf-8
"""
wirephone_channels

Munin plugin to graph number of active channels.

Created by Joao Mesquita on 2012-11-27.
Copyright (c) 2012 Indicium SRL. All rights reserved.
"""

import sys
import ESL

if len(sys.argv) > 1 and sys.argv[1] == 'config':
    print "graph_title Active Channels"
    print "graph_args --base 1000 -l 0"
    print "graph_vlabel Channels"
    print "graph_scale no"
    print "graph_category wirephone"
    print "graph_printf %3.0lf"
    print "channels.label Channels";
    print "channels.info Active channels";
    print "channels.draw AREASTACK"
    
    
    

con = ESL.ESLconnection('127.0.0.1', '8021', 'ClueCon')
e = con.api('show', 'channels count')
resp = e.getBody()
print "channels.value", resp.split()[0]
