#!/bin/sh
set -e
PKG=wirephone-supervisor-config
if [ "$1" = remove ] ; then
	[ -L /etc/supervisor/supervisord.conf ] && rm /etc/supervisor/supervisord.conf
	dpkg-divert --remove --package ${PKG} --rename \
		--divert /etc/supervisor/supervisord.conf.distrib /etc/supervisor/supervisord.conf
fi
#DEBHELPER#
exit 0
